#!/usr/bin/env ti-guile
!#

(use-modules (ubu))
(use-modules (ubu-lib adoc))

(set "adoc-prog-name" "gutman")


(define usr-install-path (car (string-split (getenv "GUILE_LOAD_PATH") #\:)))

(ubu-default "install")
(action install
        (adoc-build-man)
        (adoc-install-man)
        (sh "cp -r lib/gutman.scm" usr-install-path)
        (sh "cp -r gutsys" usr-install-path))

(action test
        (with-output
         (sh "cd test; test-gutman")))

(action clean
        (sh "rm -f test/gutman.log"))

(ubu-run-cli)
