#!/usr/bin/env ti-guile
!#

(use-modules (ubu))

(set "man-path" (cat (env "HOME") "/usr/man"))
(set "doc-src" "doc/gutman.adoc")
(set "doc-dst" "doc/GUTMAN.3")


(define usr-install-path (car (string-split (getenv "GUILE_LOAD_PATH") #\:)))

;; Build man pages.
(action build-doc
        (ubu-for-updates (get "doc-src") (get "doc-dst")
                         (lambda (src dst)
                           (sh "a2x --doctype manpage --format manpage" src "-D doc"))))

(ubu-default "install")
(action install
        (build-doc)
        (sh "cp " (get "doc-dst") (cat (get "man-path") "/man3"))
        (sh "cp -r lib/gutman.scm" usr-install-path)
        (sh "cp -r gutsys" usr-install-path))

(action test
        (with-output
         (sh "cd test; test-gutman")))

(action clean
        (sh "rm -f test/gutman.log"))

(ubu-run-cli)
