#!/usr/bin/env ti-guile
!#

(use-modules (ubu core))
(use-modules (ubu-lib path))
(use-modules (ubu-lib adoc))
(use-modules (tuile pr))

(path-refresh)

(set "adoc-prog-name" "gutman")


(define usr-install-path (get "user-install-path"))

(ubu-default "install")
(action install
;;         (adoc-build-man)
;;         (adoc-install-man)
;;         (ppre usr-install-path)
        (sh "cp -r gutman" usr-install-path))

(action test
        (with-output
         (sh "cd test; test-gutman")))

(action clean
        (sh "rm -f test/gutman.log"))

(ubu-run-cli)
