GUTMAN(3)
=======
:doctype: manpage


== NAME

GUTMAN - Guile Patch Manipulator


== VERSION

GUTMAN v0.1 (2021-11-06)


== Overview

{Gutman} (Guile Patch Manipulator) is a library for text file
patching. It can also be used to extract information from files.

== Documentation

Here is a brief overview of *Gutman*. Please refer to API
documentation for complete view. Also refer to tests for multiple ways
of how to use *Gutman*.

Typical *Gutman* script opens files for editing. File is read into the
library as content line by line. User finds the place for editing
either with Regexp searches or with direct line numbers. The file
content is edited by adding, removing, or replacing lines. When all
edits are done, the updated file content is written to disk.

    (gutman-edit "edit_me.txt"
                 (line 10)
                 (delete)
                 (write))

All editing commands refer to the "current position". Current position
is returned by "line" method. Positions refer to lines that have
content. Line numbers start from 1.

If user wants append to the end of file, then user should jump to last
line and insert text with end attribute.

It is also possible to jump to arbitrary lines, *Gutman* does not
prevent this. The line positions are just used as an index to vector
containing the lines. For example negative line number will refer from
end towards beginning in content.

Position can be explicitly changed with "line", "step", "firstline",
or "lastline" methods (commands). "find" changes position if the
pattern is found in selected direction.

    (define curline (line))
    (if (> curline 5)
        (step -2)
        (line 10))

Current line content is returned by "get" and it can be set with
"set" method. Current line content can be replaced with "sub".

    (set (glue (get) "..."))

Block commands perform commands over a range of lines. Block commands
are: do-all, do-range, and do-for. These retain the original position,
but the final position is stored (actually one after) and it can be
activated by calling "blockline" method, i.e. *Gutman* jumps to that
line.

Block commands take a pre-defined number of lines to process. Note
that, if user deletes lines in block action, the outcome is most
likely not what the user expects.

Mark feature can be used if user wants to return back to original
position after changes. Mark features includes a "default mark" and
"named marks".

    (mark 'origin)
    (step 10)
    (delete)
    (unmark 'origin)

For debugging purposes it is good to see line content. "view" and
"view-ln" can be used to view line content either without or with line
numbers respectively.

No changes are stored to disk unless "write" is called.


== Example session

    ;; Open file for reading.
    r = Gutman.read( "report.txt" )

    ;; Backup file and find next line with "error", i.e. method chaining.
    (copy "report.txt.org")
    (find "error" )

    ;; Collect some lines.
    (define data (repeat (lambda () (ref (line))) 4))

    ;; Duplicate the lines collected.
    (insert data)

    ;; Move to line 9.
    (line 9)

    ;; Append " Hello" to the end of current line.
    (set (join " " (get) "Hello"))

    ;; Save changes.
    (write)


== Action API


=== gutman-read

`gutman-read` reads lines from given file.

Syntax: `(gutman-read <filename> )`


=== gutman-edit

`gutman-edit` read lines from given file and executes the included
commands, and finally edits are saved to the file.

Syntax: `(gutman-edit <filename> <commands> ...)`

=== gutman-use

`gutman-use` takes a given gutman-state into use.

Syntax: `(gutman-use <state> <body> ...)`

=== read-file

`read-file` reads lines from given file.

Syntax: `(read-file <filename>)`

=== read-file-content

`read-file-content` reads lines from given file and returns the lines a vector.

Syntax: `(read-file-content <filename>)`

=== write-file

`write-file` writes Gutman content to disk. Write is performed either
to current file or named file.

Syntax: `(write-file [<filename>])`

=== copy

`copy` writes Gutman content to file.

Syntax: `(copy <filename>)`

=== line

`line` returns or sets the line, if "lineno" argument is given.

Syntax: `(line [<lineno>])`

=== step

`step` steps forward or backward current position. Positive value
steps forwards and negative value steps backwards.

Syntax: `(step <step>)`

=== firstline

`firstline` sets the current line to first.

Syntax: `(firstline)`

=== lastline

`lastline` sets the current line to last.

Syntax: `(lastline)`

=== blockline

`blockline` jumps to line after block target.

Syntax: `(blockline)`

=== lines

`lines` gets or sets Gutman content.

Syntax: `(lines [<line-content> ...])`

=== get

`get` current line or lines by count. Default count is 1.

Syntax: `(get [<count>])`

=== ref

`ref` returns current line or selected line.

Syntax: `(ref [<lineno>])`

=== set

`set` sets the content of current line.

Syntax: `(set <content>)`

=== has?

`has?` returns non-false if line has the string or regexp.

Syntax: `(has? <str-or-re>)`

=== glue

`glue` joins arguments without a separator.

Syntax: `(glue {<str> ...}|{<str-list>})`

=== join

`join` joins arguments with given separator.

Syntax: `(join <separator> {<str> ...}|{<str-list>})`

=== sub

`sub` substitutes part of current line content.

Syntax: `(sub <from-str-or-re> <to-str>)`

=== update

`update` updates the content of current line using the supplied "proc"
(line given as argument).

Syntax: `(update <proc>)`

=== insert

`insert` inserts lines and move to insertion position (i.e. line is
not changed). Position is current line if no position is given.

Position: <num>, 'first, 'after, 'last, 'end.

Syntax: `(insert <none-line-or-lines> [<position>])`

=== insert-step

`insert-step` inserts lines and move to last inserted line. Position
is current line if no position is given.

Position: <num>, 'first, 'after, 'last, 'end.

Syntax: `(insert-step  <none-line-or-lines>)`

=== remove

`remove` removes current line or number of lines.

Syntax: `(remove [<count>])`

=== insertfile

`insertfile` inserts file to current position.

Syntax: `(insertfile <filename>)`

=== insertfile-step

`insertfile-step` inserts file to current position and steps after it.

Syntax: `(insertfile-step <filename>)`

=== clear

`clear` clears Gutman content and reset current line.

Syntax: `(clear)`

=== find

`find` finds regexp or literal string forwards or backwards. Return
true on success.

Syntax: `(find <re-or-str>)`

=== search

`search` finds regexp or literal string forwards or backwards. Fail
with expection (gutman-search-error) if not found.

Syntax: `(search <re-or-str>)`

=== linecount

`linecount` returns line count in Gutman content.

Syntax: `(linecount)`

=== filename

`filename` returns file name of Gutman content.

Syntax: `(filename)`

=== edit

`edit` marks the current content edited.

Syntax: `(edit)`

=== edited?

`edited?` returns true if content has been edited.

Syntax: `(edited?)`

=== within?

`within?` returns true if current line is within the lines region.

Syntax: `(within? ...)`

=== excursion

`excursion` executes "proc" (a thunk), retain current position, and
return "proc" value.

Syntax: `(excursion <proc>)`

=== mark

`mark` marks (stores) current position to default or to named mark.

Syntax: `(mark <none-or-markname>)`

=== unmark

`unmark` unmarks (restores) current position from default or from
named mark.

Syntax: `(unmark <none-or-markname>)`

=== do-all

`do-all` executes given block for all lines, i.e. all
positions. "proc" parameter is Gutman.

Syntax: `(do-all <proc>)`

=== do-range

`do-range` executes given "proc" between start and stop positions, and
updates position.

Syntax: `(do-range <start> <stop> <proc>)`

=== do-for

`do-for` executes given "proc" starting from start by count, and
updates position.

Syntax: `(do-for <start> <count> <proc>)`

=== get-range

`get-range` gets lines between start and stop positions inclusive.

Syntax: `(get-range <start> <stop>)`

=== get-for

`get-for` gets lines starting from start by count.

Syntax: `(get-for <start> <count>)`

=== peek

`peek` displays line content around current position (by count or 1).

Syntax: `(peek [<count>])`

=== peek-ln

`peek-on` displays line content (with line numbers) around current
position (by count or 1).

Syntax: `(peek-ln [<count>])`

=== view

`view` displays line content.

Arguments:
 * no args:  view all
 * one arg:  view from current onwards by count
 * two args: view given range

Syntax: `(view ...)`

=== view-ln

`view-ln` displays line content with line numbers;

Arguments:
 * no args:  view all
 * one arg:  view from current onwards by count
 * two args: view given range

Syntax: `(view-ln ...)`
